services:
  usb-fan:
    image: klaspihl/usb_onoff:latest
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    privileged: true
    restart: unless-stopped
    environment:
      - TEMP_THRESHOLD_HIGH=65
      - TEMP_THRESHOLD_LOW=45
      - FREQ=30
      - UHUBCTL_LOCATION=7-1
      - UHUBCTL_PORT=2
    healthcheck:
      test: ["CMD", "pgrep", "-f", "usb_OnOff.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
